listen_addres: ":8080"
algorithm: "round_robin"
health_interval: "5s"

backends:
  - name: backend-1
    url:  "http://localhost:9001"
  - name: backend-2
    url:  "http://localhost:9002"

default_rate_limit:
  capacity: 10
  rate_per_sec: 12


